{% set name = "thop" %}
{% set version = "0.1.1.post2209072238" %}
{% set commit_id = "43c064afb71383501e41eaef9e8c8407265cf77f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # use github archive release for tests, LICENSE, and because there is no sdist on PyPi
  url: https://github.com/Lyken17/pytorch-OpCounter/archive/{{ commit_id }}.tar.gz
  sha256: cbda9dc83ad9b78a9fbc8d89f8f1fb1da8ca284b39faab3e9ed697fb2bee909f
  patches:
    - patches/0001-use-conda-build-version-for-pkg.patch

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pytorch

test:
  imports:
    - thop
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    # check that pip gets the correct version
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests

about:
  home: https://github.com/Lyken17/pytorch-OpCounter
  summary: Count the MACs / FLOPs of your PyTorch model.
  description: |
    Count the MACs / FLOPs of your PyTorch model.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/Lyken17/pytorch-OpCounter
  doc_url: https://github.com/Lyken17/pytorch-OpCounter

extra:
  recipe-maintainers:
    - lorepirri
